name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@103.119.170.144 << 'EOF'
            cd weaveBI
            source .venv/bin/activate

            pkill -f 'uvicorn main' || echo "Couldn't kill uvicorn process"

            git pull origin main

            alembic upgrade head

            nohup uvicorn main:app --host 0.0.0.0 --port 8080 > /dev/null 2>&1 &

            exit
          EOF
